version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-muliple-web-network



  python:
    depends_on:
      - db
    image: crud
    ports:
      - 8080:8080
    networks:
      - my-muliple-web-network


networks:
  my-muliple-web-network:
    driver: bridge